name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup-build-env:
    uses: ./.github/workflows/lib/setup-build-env.yml
    secrets: inherit

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run ci:version
          publish: pnpm run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy Docs When Package Was Published
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        run: echo "Deploy Stub"
